### ISSUE TITLE
Share core functionality with size-plugin?

### ISSUE THREAD

**Issue by developit** [luwes/rollup-plugin-size#1]
Hi @luwes!

I'm wondering if we should figure out a way to share the core size calculation and display logic between the two plugins so they can receive the same updates (in particular, GoogleChromeLabs/size-plugin#15). Thoughts?

**Comment by luwes** [comment]
That would be super neat! I'm all for that.

I mostly used the `outputSizes` and `getSizes` functions, removed `reverseTemplate` I thought this was specific to Webpack, though the hash logic might have to be put back. I didn't try this yet with code splitting only with multiple bundles builds.

For this the default `columnWidth` was added because multiple bundles wouldn't know about each other beforehand I think.

One bit in `outputSizes` changed from `assets[name].source()` to `assets[name].code`.

Let me know if I can be of help for the core functionality.
Would they be exposed from `size-plugin` or another isolated pkg?

**Comment by luwes** [comment]
Would love that history functionality 😃 
We actually NEED that at work, take my size graph to meetings haha

**Comment by developit** [comment]
Just an update from me, I still want this but haven't had time to hack on anything.

**Comment by kuldeepkeshwar** [comment]
@developit @luwes I gave it a try [size-plugin-core](https://github.com/kuldeepkeshwar/size-plugin-core), please review

PRs
- [size-plugin](https://github.com/GoogleChromeLabs/size-plugin/pull/27)
- #4

**Comment by developit** [comment]
Might be nice to expose a method that lets folks populate `sizesBefore` before calling `outputSizes`. Also maybe make it a class?

**Comment by kuldeepkeshwar** [comment]
@developit / @luwes I have updated the code.
Added option to override any step performed by `size-plugin-core`.

e.g
```js
const sizesBefore = await getPreviousSizes(outputPath) ;
const sizes = await getSizes(assets); 
const files = await getDiff(sizesBefore,sizes); // calculate the diff
const output = await printSizes(files); // template output message
await uploadSizes(files); // upload stats
return output;
```
